### ISSUE TITLE
Add DEdC Logo

### ISSUE THREAD

**Issue by eugene-davis** [IndustrialDragonfly/DEdC#1]
![logo](https://f.cloud.github.com/assets/5706175/1369630/4645d792-39fa-11e3-8fe4-8b4f17ca6678.png)
I created a logo for DEdC recently, can you either add it or replicate it in HTML?
The font can be changed (either in the image, or if you replicate in HTML), but the color scheme and positioning and size of the C (that is a bit larger, and centered so that part of it dips below the line of the rest of the text) should stay about the same.

I can get you the original SVG or an bitmap format, as well as changing the font on the image.

**Comment by jacob-swanson** [comment]
That image is now the logo.
