### ISSUE TITLE
image for data store incorrect

### ISSUE THREAD

**Issue by JoshuaJClark** [IndustrialDragonfly/DEdC#2]
the image for the data store is incorrect, right now it appears as a square which is the image for the external interactor, this image needs to be two parallel lines on the top and bottom

**Comment by jacob-swanson** [comment]
I couldn't make a rectangle with a stroke on just the top and bottom, so I just left it as it is. All of the icons should probably be stored externally instead of created in html.

**Comment by eugene-davis** [comment]
The only approaches I saw to creating two parallel lines like that was to just do two lines, or alternatively use a dash pattern - I think defining two lines separately is the better approach.
That being said, if we can figure out a good way to do it, I agree that the icons should probably be stored outside of the HTML.

**Comment by JoshuaJClark** [comment]
if you can change the color of each line segment maybe we could make just the top and bottom lines black and the side lines white (or whatever color the background is)

**Comment by jacob-swanson** [comment]
I fixed this by using two paths for the lines and a white rectangle for the fill.
