### ISSUE TITLE
Check that addLink in Node is only called by Link

### ISSUE THREAD

**Issue by eugene-davis** [IndustrialDragonfly/DEdC#20]
The addLink function should only be called by a Link type object, otherwise it may add a link without the Link showing as being connected to it.

Should function like a Friend in C++, but preferably locked down to just this function.

**Comment by eugene-davis** [comment]
Look at https://stackoverflow.com/questions/190421/caller-function-in-php-5
Basically this let's you get a stack trace and figure out who called you http://uk.php.net/manual/en/function.debug-backtrace.php

A bit ugly, but maybe a good way to go.

**Comment by JoshuaJClark** [comment]
used 
$trace=debug_backtrace();
        $caller=array_shift($trace);
        $caller=array_shift($trace);
        if($caller['class'] != 'Link')
        {
            throw new BadFunctionCallException("addLink() was not called by a Link object");
        }
