### ISSUE TITLE
closing the tabs on the left

### ISSUE THREAD

**Issue by JoshuaJClark** [IndustrialDragonfly/DEdC#3]
should we be able to close the left side tabs, currently we cannot, is this the behavior we want?

**Comment by eugene-davis** [comment]
Eventually they need to close, for the time being we can just add a button to close them that doesn't yet need functionality.

**Comment by jacob-swanson** [comment]
The jquery layout plugin allows you to collapse the whole panel if that's what you're talking about.

**Comment by eugene-davis** [comment]
No, this refers to the DFD and Firing Control tabs.

**Comment by JoshuaJClark** [comment]
actually what I meant is the elements layers and users tabs, should they all be close-able at the same time,

**Comment by jacob-swanson** [comment]
You can now close all of the tabs in the left pane including the nested users one. The first tab is still open by default.
