### ISSUE TITLE
DFD Data Model needs to be thoroughly documented

### ISSUE THREAD

**Issue by eugene-davis** [IndustrialDragonfly/DEdC#38]
The DFD Data Model needs to have all member variables and functions clearly and understandably documented.
This is probably best effected by using PHP Doc comments above each attribute/function and running API Gen on the code.

**Comment by JoshuaJClark** [comment]
should i do this on everything or just everything that is public?

**Comment by eugene-davis** [comment]
Just public needs to be provided in the documentation, but private variables should have good comments as well.

**Comment by eugene-davis** [comment]
APIGen let's us use the fairly thorough existing comments.
