### ISSUE TITLE
left side scroll bar 

### ISSUE THREAD

**Issue by JoshuaJClark** [IndustrialDragonfly/DEdC#4]
interacting with the scroll bar on the left side causes the panel to act strangely; if you click and drag on the bar everything vanishes and reappears.  if you drag the bar up and let go the entire side panel vanishes and will not come back

**Comment by jacob-swanson** [comment]
I have not added any resizing code for the jquery ui elements at this time, so that may be the problem.

**Comment by eugene-davis** [comment]
I think he means moving the scroll bar causes problems, not resizing the panel itself.

**Comment by jacob-swanson** [comment]
Fixed this by adding the resizing stuff for both the sidebar and the tab content.
