### ISSUE TITLE
originator attibute in the DataFlowDiagram class

### ISSUE THREAD

**Issue by JoshuaJClark** [IndustrialDragonfly/DEdC#40]
you added a originator attribute to DFD, what is it used for and is it different than the originator attribute in the Entity class?  if it is different we need a new name as this one will override the currently existing one in the entity class.  note the orginator in Entity is basically unused by anything its just a string intended to hold the name of the user that created it

**Comment by eugene-davis** [comment]
No, same thing, just forgot it was in entity. You can and should remove it from DFD.
