### ISSUE TITLE
Consider making enumeration for generic types to use in Request/Response and Data Model

### ISSUE THREAD

**Issue by eugene-davis** [IndustrialDragonfly/DEdC#46]
Since under the constraint that every object must inherit from the DFD, Link, Node or SubDFDNode type when extending the data model, it seems that this is a prime candidate for using enumeration to prevent mistakes. The two locations affected should be in the Response objects (maybe in the Request objects) and the Entity class of the Data Model where the genericType is set in the getAssociativeArray function.

**Comment by JoshuaJClark** [comment]
wouldn't this conflict with the extensibility to for a user to add their own custom node/link objects

**Comment by eugene-davis** [comment]
No, there is a difference between the type and the genericType. We are not supporting the ease of extensibility of the basic types (Link, Node, SubDFDNode, Diagram) only extensions of them (and extensions of those extensions if desired).

**Comment by eugene-davis** [comment]
Don't think I'm going to worry about this for the time being. We may opt to look at it again in the future.
