### ISSUE TITLE
associative arrays for linkList and NodeList in DatabaseStorage.php

### ISSUE THREAD

**Issue by JoshuaJClark** [IndustrialDragonfly/DEdC#65]
currently these arrays load everything from the DB these need to be refined down to 
linkList: id and label;
nodeList: id, label and position;

**Comment by eugene-davis** [comment]
For which thing, loading a diagram or for the individual node and link elements?

**Comment by JoshuaJClark** [comment]
the associative arrays of llinks and nodes inside a diagram object

**Comment by eugene-davis** [comment]
Appears I already did this.
