### ISSUE TITLE
"_id" being appended to diaNode even when diaNode null

### ISSUE THREAD

**Issue by jacob-swanson** [IndustrialDragonfly/DEdC#66]

**Comment by JoshuaJClark** [comment]
what field is this attached to? id? or is this not a model issue?

**Comment by eugene-davis** [comment]
This is a problem with the associativeArrayManager library. It is currently captured in a TODO, basically everything needs to be wrapped in an if statement to see if it is null when add tag is doing its thing.

**Comment by eugene-davis** [comment]
This appears to resolve the issue here, but may have made the issue mentioned in issue #69 appear more often.
