### ISSUE TITLE
Links originNode and destinationNode are not saved correctly.

### ISSUE THREAD

**Issue by jacob-swanson** [IndustrialDragonfly/DEdC#68]
The text "Array" is inserted into the originNode and destinationNode fields in the link table. Also, _id is not stripped from them.

**Comment by IndustrialDragonfly** [comment]
Isn't this two separate issues?
1) "Array" is inserted into the originNode and destinationNode fields
2) _id is not stripped from them correctly

**Comment by eugene-davis** [comment]
I don't see the _id thing occurring. Please confirm that confirm that my commit fixed your bug, and if _id is not being stripped, make a new issue. Reopen this issue if you still are not seeing them saved.
