### ISSUE TITLE
Rename Originator to userName

### ISSUE THREAD

**Issue by jacob-swanson** [IndustrialDragonfly/DEdC#72]
Originator is confusing and does not map very well to the user model.

**Comment by JoshuaJClark** [comment]
should we leave this as a string or should it be a User object (or the ID of a User object)?

**Comment by eugene-davis** [comment]
It will be the ID of a user object.
Don't worry about this, Jacob and I will handle this when we do the authentication work - just get the data model knocked out.

**Comment by eugene-davis** [comment]
Renamed to user in the end.

**Comment by JoshuaJClark** [comment]
does this still need to be updated in the DB? this should be done just so we are consistent

**Comment by eugene-davis** [comment]
It has been done on my branch. Not yet pushed. You really DON'T want my branch just yet. But soon.

**Comment by eugene-davis** [comment]
Actually, we may change a little more for consistency, we need an owner attribute within the objects, which can be compared to the user passed in. This doesn't matter yet, but will to handle organizations (needed for multiuser)
